language: scala
sudo: false
jdk: openjdk8
scala:
- 2.12.12
- 2.13.3
script:
- sbt
  "++ ${TRAVIS_SCALA_VERSION}"
  "all scalafmtSbtCheck scalafmtCheckAll scalaParser/scalafmtCheckAll"
  test
  "scalaParser/testOnly scalaparser.SnippetSpec"
matrix:
  include:
  - scala: 2.12.12
    jdk: openjdk11
    dist: xenial
